### ISSUE TITLE
Custom Dimension with pageview

### ISSUE THREAD

**Issue by wallstudios** [danwilson/google-analytics-plugin#95] opened 2015-04-23 00:42 UTC
Hi there,

Just wondering if there is support to send a custom dimension or custom metric with a page view or event?

currently you have support to set a custom dimension which works well. But if I only want to send one based on a page view or event.
As per google...
https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets#sendingdata

								ga('send', 'pageview', {
								'dimension15':  'My Custom Dimension'
								});

								
								ga('send', 'event', 'category', 'action', {
								'metric19': 24.99
								});

and yours

								window.analytics.trackEvent('Category', 'Action', 'Label', Value)

I tried this but it didn't work. 

								window.analytics.trackEvent(''Category', 'Action', {
									  '1': "test 1"
								});

thanks

**Comment by danwilson** [comment] 2015-05-20 18:07
Duplicate of #64 - will look into this.

**Closed by danwilson** 2015-05-20 18:07 UTC
Labels: duplicate

**Comment by souly1** [comment] 2016-02-28 21:14
Added a pull request to support sending a custom metric according to 
[](https://developers.google.com/analytics/devguides/collection/android/v4/customdimsmets)
and 
[](https://developers.google.com/analytics/devguides/collection/ios/v3/customdimsmets)

Works on Android, not tested on iOS, so...
https://github.com/danwilson/google-analytics-plugin/pull/204

**Comment by seme1** [comment] 2016-08-22 08:27
was this ever implemented ?

**Comment by victorsosa** [comment] 2016-08-22 11:36
@seme1 Yes, since version 0.9.0; I have to check you point.

**Comment by victorsosa** [comment] 2016-08-22 21:53
Hi, @seme1 

only session-based custom dimensions, the case of custom metric is different and more like the feature you looking for. But on custom dimensions, If you don't want a custom dimension value with session or user-level scope to be applied to past hits in the current session, start a new session before applying the value to a hit and this will works too. But we don't have the new session feature in this plug-in, yet (easy to implement, PR is welcome)

Base on what I read on the docs.

> Considerations for Custom Dimensions
> 
> Values with User and Session-Level Scopes Apply to Past Hits
> 
>     Custom dimension values with user or session-level scope will apply to all hits in the current session, including past hits. If you don't want a custom dimension value with session or user-level scope to be applied to past hits in the current session, start a new session before applying the value to a hit.
>     For example, if you're using membership type as a user-level custom dimension, and a user upgrades their membership in the middle of a session, you may want to start a new session before you set the new custom dimension value. This ensures that the hits prior to the upgrade will be associated with the old membership value, while new hits will be associated with the new value.
> 
> Custom Dimensions and View (Profile) Filters
> 
>     User or session-level custom dimension values will still be applied to all hits in the current and/or future sessions even if the hit they are sent with is filtered from a view (profile) .
>     When filtering on a custom dimension value, hits are filtered according to the scope of that custom dimension value. Learn more about how filters and custom dimension values interact when your data is processed.

https://developers.google.com/analytics/devguides/collection/android/v4/customdimsmets

**Comment by victorsosa** [comment] 2016-08-22 21:56
releated to #71
