### ISSUE TITLE
Library size is over 32MB

### ISSUE THREAD

**Issue by hoverpin** [danwilson/google-analytics-plugin#377] opened 2017-02-27 13:57 UTC
The libGoogleAnalyticsServices.a is over 32MB and bloat our app. Is there anyway to reduce the size? It's probably better to use the javascript library directly instead of this plugin.

**Comment by victorsosa** [comment] 2017-02-28 15:30
We can fix this using cocoapods, this plugin could help us:
https://github.com/blakgeek/cordova-plugin-cocoapod-support

**Comment by jvence** [comment] 2017-02-28 15:47
+1

**Comment by dodomui** [comment] 2017-06-11 13:51
I just install through NPM and check the version is 1.8.2.
Wonder is 1.9.0 released already?

Was this problem solved?

My IOS app was grow until 55MB already. While android is 30MB. Wonder is it caused by this issue?
Still tacking the root caused.

**Comment by victorsosa** [comment] 2017-06-24 20:49
Hi,
Please help me to test this out; I have a fix for this issue; you should be able to get the code on the branch cocoa_pops and test the fix for this issue.

Let me know any issue.

**Comment by dodomui** [comment] 2017-06-25 04:27
Thanks.
But the app size of IOS still the same, around 50MB++

Did I miss anythings? 

1. I update the plugin.xml based on your branch.
2. Install cocoa pod plugin using CLI.
cordova plugin add cordova-plugin-cocoapod-support --save

While I build IOS through CLI saw this alert. Will it be something I miss?
...
Checking config.xml for pods.
No new pods detects

Ah man!. It doesn't look like you have CocoaPods installed.

You have two choices.

1. Install Cocoapods:
$ sudo gem install cocoapods
2. Manually install the dependencies.

I did try sudo gem install cocoa pods, but no respond

**Comment by victorsosa** [comment] 2017-06-25 11:29
before compile run `pop install`

**Comment by victorsosa** [comment] 2017-06-25 11:39
Never mind I found the issue the import is incorrect.
#import "GAI.h"
and it should be:
#import <Google/Analytics.h>

I will do the change and let you know

**Comment by victorsosa** [comment] 2017-06-25 11:45
Please check again; imports fixed

**Comment by victorsosa** [comment] 2017-06-28 06:56
@dodomui everything is ok?

**Comment by dodomui** [comment] 2017-06-28 12:59
@victorsosa sorry for late reply.

Thanks for the update. 
I installed with the 1.8.3 version. But the size of App doesn't go down.
IOS app was 55MB previously and now is 54MB ^^".

@hoverpin do you still face the same problem with this release?
Because I didn't found out what cause my IOS app cost double of size than Android app yet.

**Comment by victorsosa** [comment] 2017-06-28 13:06
@dodomui remember you should test using the branch cocoa_pops

**Comment by victorsosa** [comment] 2017-06-28 13:08
@dodomui I will reduse the size of the package when you confirm that is working using the cocoa_pops branch

**Comment by dodomui** [comment] 2017-06-30 10:05
@victorsosa, may I know where is the file of #import <Google/Analytics.h>?
The problem is cannot find locate this file.

**Comment by victorsosa** [comment] 2017-06-30 11:52
@dodomui 
it should be install after the pop install the package. you can check the docs here:
https://developers.google.com/analytics/devguides/collection/ios/v3/

You should install the branch cocoa_pops using this command:
cordova plugin add https://github.com/danwilson/google-analytics-plugin.git#cocoa_pops

**Comment by dodomui** [comment] 2017-07-01 05:20
@victorsosa 
I did try 
```
pod init
pod 'Google/Analytics'
pod install
```
All this is working fine.

But until I try build ios project then meet below problem.
Error: Error code 65 for command: xcodebuild with args: -xcconfig

I am new to those area and causing you lot of trouble I think.
I will continue use current version 1.8.3 i think.

But another question that I more concern is regarding the IDFA, will 1.8.3 having same issue? and being rejected by Apple store?

**Comment by victorsosa** [comment] 2017-07-01 11:16
please check comments on issue #218 for that

**Comment by fdambrosio** [comment] 2017-09-06 10:42
+1

**Comment by VDBento** [comment] 2018-02-20 17:18
Hi @victorsosa, 

Thank you for your effort on maintaining the plugin.
Have you got any updates on this?
I am facing the same issue. I would like to use the plugin, but I can't have one single file with more than 30MB on the app.

Thanks in advance!

**Comment by patrickbussmann** [comment] 2019-10-31 23:58
Do you have any news here?
I now installed the plugin and the app increases too crazy 😅
How to solve this size?

**Comment by victorsosa** [comment] 2020-04-01 16:22
fix to be release on 1.9

**Closed by victorsosa** 2020-04-01 16:22 UTC
Labels: Help Wanted, enhancement
