### ISSUE TITLE
setAnonymizeIp for privacy issues

### ISSUE THREAD

**Issue by jeresiv** [danwilson/google-analytics-plugin#119] opened 2015-06-24 18:35 UTC
I need to be able to set anonymizeIP to true for privacy concerns can a method or flag be added for this functionality?

https://developers.google.com/android/reference/com/google/android/gms/analytics/Tracker#setAnonymizeIp(boolean)

**Comment by Hirbod** [comment] 2015-06-27 01:41
+1

**Comment by mpoisot** [comment] 2015-07-06 22:14
duplicate of #83

**Comment by danwilson** [comment] 2015-10-27 17:37
Duplicate of #83

**Closed by danwilson** 2015-10-27 17:37 UTC
Labels: duplicate
