### ISSUE TITLE
Shall I resend session scope custom dimension after session timeouts?

### ISSUE THREAD

**Issue by Sollll** [danwilson/google-analytics-plugin#441] opened 2017-07-10 22:29 UTC
Hi. A question about sessions and custom dimension.
On google docs I read: 
```
By default, a session lasts until there's 30 minutes of inactivity
```
My custom dimension has session scope.
So the question is - shall I set my custom dimension with **window.ga.addCustomDimension()** after each 30 minutes of inactivity?

**Comment by victorsosa** [comment] 2017-07-10 22:38
No, the customDimension will be set permanently. But it will count one every session.

**Comment by Sollll** [comment] 2017-07-10 22:48
@victorsosa Thanks for quick reply! :)
1) So, if I don't want to have old value on the new session(which starts after timeout or manually)  then I shall set custom dimension to '' or some new value?
2) After application restart will it be clean or have value from last time?

**Comment by victorsosa** [comment] 2017-07-10 22:51
1. you can do it manually by creation a new session. check the readme about it.
```
//To track a Screen (PageView) and create a new session:
window.ga.trackView('Screen Title', '', true)
```
2. clean

**Comment by Sollll** [comment] 2017-07-10 22:56
1a. So creating new session via trackView or trackEvent will reset all custom dimensions?
1b. As opposite - when new sessions created because of timeout it does not reset dimensions?

**Comment by Sollll** [comment] 2017-07-11 07:07
@victorsosa I tried to test it...
```
window.ga.addCustomDimension(1, 'testSessionsDimension')
window.ga.trackView('testSessionsView1')
window.ga.trackEvent('testSessionsEvent1', 'testSessionsEvent1', 'testSessionsEvent1')
event onPause 
... here I left my tablet for 40+ minutes to get automatic session start
event onResume 
window.ga.trackView('testSessionsView2')
window.ga.trackEvent('testSessionsEvent2', 'testSessionsEvent2', 'testSessionsEvent2')
event onPause 
event onResume
window.ga.dispatch()
window.ga.trackEvent('testSessionsEvent3', 'testSessionsEvent3', 'testSessionsEvent3',0,true)
window.ga.trackView('testSessionsView3')
window.ga.dispatch()
... Then I restarted application and entered
window.ga.trackView('testSessionsView4')
window.ga.trackEvent('testSessionsView4', 'testSessionsView4', 'testSessionsView4')
```

And in ga all screens have dimension set to testSessionsDimension... even after application restart.
Why is it this way?

![Google analytics](http://i64.tinypic.com/167o9xt.png)

**Comment by victorsosa** [comment] 2017-07-11 10:28
Do you want to use another dimension or reset the dimension?
use another dimension:` window.ga.addCustomDimension(2, 'testSessionsDimension2')`
reset: `window.ga.addCustomDimension(1, '')`

**Comment by Sollll** [comment] 2017-07-11 12:16
@victorsosa 
**I want to understand - if I set value to dimension that has session scope, when it will be reset?**
 As I understand from ga docs, it should apply only to current ga session! Thats the point of session scope...
Will it be reset on:
1) Application restart? You told me that after restart it would be clean, but somehow ga shows me that it is still set.. - check my previous post - **testSessionsView4** should not have **testSessionsDimension** value...
2) Session timeout (as I understand it should be reset on timeout, because it was set only for current session(session scope param))?
3) Manual start of new session(using trackEvent and trackView with last parameter true)?

**Comment by victorsosa** [comment] 2017-07-13 09:44
plase check comment on #415; there is a bug with this.

**Comment by spacepope** [comment] 2017-07-13 16:23
I added PR https://github.com/danwilson/google-analytics-plugin/pull/443 to provide the possibility to unset custom dimensions and metrics.

@Sollll to understand how this plugin works (on Android and Windows) with custom dimensions and metrics: on every call to addCustomDimension or trackMetric an entry is added to an internal dictionary. Then on every call to trackView, trackEvent, trackException, etc.. all custom dimensions and metrics are added to the hit via HitBuilder classes and sent to Analytics.
As far as i know Google Analytics Backend then computes the dimensions and metrics on behalf of your scope settings (Hit, Session, Product, ...). If you want to know more, read the [Google Analytics Docs for Android](https://developers.google.com/analytics/devguides/collection/android/v4/customdimsmets)

So if i get it right: if you selected Session scope for your dimension, it should only be unset (at the analytics backend) by starting a new session, which as @victorsosa pointed out is possible by tracking a view with third parameter set to true.
(Additionally you would have to unset the custom dimension / metric, otherwise it is added again to the next hit sent... Thats why i submitted a PR..)

I never did so much custom dimensions / metrics and just transcribed the Android algorithm to Windows platform.
But, @victorsosa, perhaps the Android behaviour on this was not the right way of handling this before..
Look at the iOS implementation for trackMetric: there the metric is set directly on the tracker object with `[tracker set:[GAIFields customMetricForIndex:[key intValue]] value:value];`, no internal dictionary. But thats not consistent as a dictionary is used for custom dimensions and added on every hit tracked like on Android - why is it that way? 

In the setup pages for custom dimensions and metrics google proposes the following code snippets for
Browser:
```javascript
var dimensionValue = 'SOME_DIMENSION_VALUE';
ga('set', 'dimension1', dimensionValue);

var metricValue = '123';
ga('set', 'metric1', metricValue);

```
Android:
```Java
String dimensionValue = "SOME_DIMENSION_VALUE";
tracker.set(Fields.customDimension(1), dimensionValue);

String metricValue = SOME_METRIC_VALUE_SUCH_AS_123_AS_STRING;
tracker.set(Fields.customMetric(1), metricValue);
```
and iOS:
```ObjectiveC
NSString *dimensionValue = @"SOME_DIMENSION_VALUE";
[tracker set:[GAIFields customDimensionForIndex:1] value:dimensionValue];

NSString *metricValue = SOME_METRIC_VALUE_SUCH_AS_123_AS_STRING;
[tracker set:[GAIFields customMetricForIndex:1] value:metricValue];
```
Furthermore it is stated that custom dimensions and metrics only have to be sent once.

Could it be, that we potentially can get rid of all the internal dictionary stuff and do it this way on all platforms?

**Comment by victorsosa** [comment] 2017-07-14 07:14
iOS implementation use dictionary too.

`Could it be, that we potentially can get rid of all the internal dictionary stuff and do it this way on all platforms?`
NO

You should do the same implementation for all platforms in the PR #443; no just Android

**Comment by spacepope** [comment] 2017-07-14 14:08
>iOS implementation use dictionary too.

Only for custom dimension, not for trackMetric.

> _Could it be, that we potentially can get rid of all the internal dictionary stuff and do it this way on all platforms?_
>NO

Ok, i revisited the docs and _assume_ that we have to resend custom dimension/metric on every hit, because there is no method to attach this on a specific hit, right?
(I got confused by the fact that the value has only to be send once, if the dimension/metric scope is set to session or user..)

Please be a bit more informative in the future - a simple "NO" is a tough one for collaboration.

>You should do the same implementation for all platforms in the PR #443; no just Android

I changed it for Windows too. And that's the cause i am asking that question: during implementation i noticed that it _IS NOT_ the same for all platforms (and _WAS NOT_ before i started to participate)! See the Browser implementation, there is no dictionary at all!
So @victorsosa, you as the project maintainer have to at least either give a hint, if and why on Browser it is sufficient to do a simple ga.set(..) without any dictionary, or if it's not sufficient propose / ask for a change of the implementation. The same goes for iOS.

If wanted i could implement the same dictionary handling for Browser like on Android and Windows.
But i currently have no OS X machine and therefore cannot test iOS implementation and because of that **i will not touch iOS implementation!** (coding blindly is feasable but not good practice..)
This has to be done by someone else..

**Comment by victorsosa** [comment] 2017-07-14 14:24
> Please be a bit more informative in the future - a simple "NO" is a tough one for collaboration.

Sorry about that; the idea is to keep most of the current implementation as possible.

**Comment by victorsosa** [comment] 2017-07-14 14:29
What do you think is the best approach to implement this then? what should we do?

**Comment by spacepope** [comment] 2017-07-14 14:51
>the idea is to keep most of the current implementation as possible.

Yes, i absolutely agree on this.
So if the current implementation is working on Browser, there is no need to touch it.

I think the overall confusion regarding custom dimensions is because of the slightly different approach  this plugin API took and the original Google Analytics SDKs point of view..
But i think we should not put too much effort on this because Google now hardly pushes Firebase SDK for mobile analytics..

Perhaps @Sollll could test the code from my PR (just clone my fork with `git clone https://github.com/spacepope/google-analytics-plugin.git` and then switch branch with `git checkout customDimensionAndMetricUnset`). **Only for testing purpose! The branch will be deleted after successful merge back into the main project!**
If it works the expected way on Android, someone can still alter the iOS implementation the same way.

**Comment by victorsosa** [comment] 2017-07-14 14:54
The iOS implementation use to dictionaries `customMetricForIndex` and `customDimensionForIndex`; one for metric and one for customDimensions; The custom metric is the one you see is using directly because is only for metrics. 

The issue here is that the customDimensions can't be reset. But with the change in the parameter that you fix has it should work in the same way as in Android. And the customMetric doesn't need change like you mention.

**Comment by spacepope** [comment] 2017-07-14 15:34
Yes, i see the mentioned methods, but i don't get why on iOS there is an extra dictionary `_customDimensions` on plugin code which is filled in `addCustomDimension()` and then attached to the tracker on each hit via `customDimensionForIndex` within `addCustomDimensionsToTracker()` (which is the same behaviour like on Android and Windows for both dimensions and metrics, except the HitBuilder..), whereas there is no equivalent dictionary for the metrics on iOS and the metrics are added directly via `customMetricForIndex` within `trackMetric` (which was the same behaviour on Android but was fixed by my PR https://github.com/danwilson/google-analytics-plugin/pull/437).. 

Nevertheless without the possibillity to test and debug the iOS implementation i am a bit out of focus here..
So i trust in your opinion that it just works the way it is. ;)
And if someone raises an issue on the iOS implementation in the future, we can still address this..

**Comment by spacepope** [comment] 2017-07-14 15:42
@Sollll which platform are you using?

**Comment by Sollll** [comment] 2017-07-14 19:14
@spacepope I use online phonegap builder to build android app.
I don't understand why dictionary is used. As I understand methods should work same way as described on google docs, to keep consistent behaviour.
From your and @victorsosa posts I understand that all params once have been set remain so until not set to ''... If there are reasons for that - then ok - but looks like a temporary fix?  :)

**Comment by spacepope** [comment] 2017-07-15 14:49
@Sollll This plugin exists quite a while and i am contributing code only for a short time, so i don't want to turn the whole code upside down.
At first i submitted a fix to the Android implementation, where trackMetric produces a view hit every time, which was unwanted behaviour. So i adjusted it do it exactly the way it was implemented within addCustomDimension on Android, at which i apparently forgot to think about unsetting the values (as you luckily pointed out..). Thats why i submitted the latest PR. 
Keeping all the platform implementation identically is often hard to realize because the different platform SDKs not always provide the same way to do things (f.e. Android relies on a HitBuilder, which is not available on Browser..). 

So you shouldn't worry about implementation details too much and see if the fix proposed in my PR (see comment above) results in the behaviour you expect (or if it is possible to achieve the thing you want) and give us a feedback on this. That would be great..
Or submit a PR by yourself ;)

**Comment by Sollll** [comment] 2017-07-15 18:37
@spacepope unsetting custom dimensions with addCustomDimension(1, ""); looks ok for me. 
Also I think it would be nice to have a method(mb in next versions) to check current dictionary, to see what values are there already. 
I'm afraid that submitting a PR would be too hardcode for my current level :)

**Comment by victorsosa** [comment] 2017-07-18 12:38
on release 1.9.0

**Closed by victorsosa** 2017-07-18 12:38 UTC
Labels: bug
